### ISSUE TITLE
i am getting 500 error

### ISSUE THREAD

**Issue by ramonov** [adhishlal/Firebase-PHP#1]
I am using this code from codeigniter But i am getting 

<HTML>
<HEAD>
<TITLE>Internal Server Error</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Internal Server Error</H1>

<H2>Error 500</H2>

</BODY>
</HTML>

**Comment by adhishlal** [comment]
Hi Romonov,

500 Error normally comes when there is some incorrect database code/query. Kindly share your code and table structure. Would love to help.

**Comment by ramonov** [comment]
thanks adhish. I have solved the issue by now.
