### ISSUE TITLE
Getting unauthorized error

### ISSUE THREAD

**Issue by jessicastorm1986** [adhishlal/Firebase-PHP#6]
My url is - http://sco7.com/test/sendnotification.php?id=dDB8KSuRAyw:APA91bHFwRl5Kzsld_O9nydAOP3Nc-asuVSv7VYBPasHwxr-Lq8ab_t5wC6htzVLqJAv9wC057EmmJEK6grU5bb5ETZQSkcXpPu1yiBW_2JiBN8DmZEKD1495O9ER25Flg6Yf-8pXY9Y&title=Hey!&body=How%20are%20you?

Please help, why am i getting this error on your script

**Comment by adhishlal** [comment]
Use your own firebase key
