### ISSUE TITLE
How to delete specific push notification from API server

### ISSUE THREAD

**Issue by melounek** [adhishlal/Firebase-PHP#8]
It's probably not an issue, but do you have an idea how to extend this script to be able delete notification created by this script?

I specified this issue also here: https://stackoverflow.com/questions/45595760/how-to-delete-specific-push-notification-from-api-server

I just need to resolve this somehow, because without deleting created notifications is this script poor for most of purposes.

thanks

**Comment by adhishlal** [comment]
you can delete it from the firebase console directly
